name: Create Shortcut Ticket

on:
  issues:
    types: [opened]

jobs:
  create-shortcut-ticket:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Shortcut ticket
        env:
          SHORTCUT_API_TOKEN: ${{ secrets.SHORTCUT_API_TOKEN }}
          SHORTCUT_PROJECT_ID: ${{ secrets.SHORTCUT_PROJECT_ID }}
          SHORTCUT_WORKFLOW_STATE_ID: ${{ secrets.SHORTCUT_WORKFLOW_STATE_ID }}
        run: |
          ISSUE_TITLE="${{ github.event.issue.title }}"
          ISSUE_BODY="${{ github.event.issue.body }}"
          curl -X POST "https://api.app.shortcut.com/api/v3/stories" \
          -H "Content-Type: application/json" \
          -H "Shortcut-Token: $SHORTCUT_API_TOKEN" \
          -d "{
            \"name\": \"$ISSUE_TITLE\",
            \"description\": \"$ISSUE_BODY\",
            \"workflow_state_id\": $SHORTCUT_WORKFLOW_STATE_ID
          }"