name: Create Shortcut Ticket

on:
  issues:
    types: [opened]

jobs:
  create-shortcut-ticket:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract labels
        id: extract_labels
        run: |
          echo ${{ github.event.issue.labels }}
          LABELS=$(echo '${{ toJson(github.event.issue.labels) }}' | jq -r '.[].name')
          echo "LABELS=$LABELS" >> $GITHUB_ENV

      - name: Check for specific label
        run: |
          echo "Labels: $LABELS"
          if [[ "$LABELS" != *"bug"* ]]; then
            echo "Label 'bug' not found. Exiting."
            exit 0
          fi

      - name: Create Shortcut ticket
        env:
          SHORTCUT_API_TOKEN: ${{ secrets.SHORTCUT_API_TOKEN }}
          SHORTCUT_PROJECT_ID: ${{ secrets.SHORTCUT_PROJECT_ID }}
          SHORTCUT_WORKFLOW_STATE_ID: ${{ secrets.SHORTCUT_WORKFLOW_STATE_ID }}
        run: |
          ISSUE_TITLE="${{ github.event.issue.title }}"
          ISSUE_BODY="${{ github.event.issue.body }}"
          RESPONSE=$(curl -s -X POST "https://api.app.shortcut.com/api/v3/stories" \
            -H "Content-Type: application/json" \
            -H "Shortcut-Token: $SHORTCUT_API_TOKEN" \
            -d "{
              \"name\": \"$ISSUE_TITLE\",
              \"description\": \"$ISSUE_BODY\",
              \"workflow_state_id\": ${{ secrets.SHORTCUT_WORKFLOW_STATE_ID }}
            }")
          echo "Response: $RESPONSE"
          STORY_ID=$(echo $RESPONSE | jq -r '.id')
          if [[ -z "$STORY_ID" || "$STORY_ID" == "null" ]]; then
            echo "Failed to extract story ID."
            exit 1
          fi
          echo "STORY_ID=$STORY_ID" >> $GITHUB_ENV

      - name: Comment on GitHub issue
        if: success() && env.STORY_ID != 'null'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          STORY_ID=${{ env.STORY_ID }}
          COMMENT_BODY="Shortcut story created: [ID: $STORY_ID](https://app.shortcut.com/flynn-industries/story/$STORY_ID)"
          curl -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER/comments \
            -d "{\"body\":\"$COMMENT_BODY\"}"